apiVersion: v1
kind: Service
metadata:
  name: classifi-cat-or
  namespace: dhge
spec:
  ports:
  - port: 5000
  selector:
    app: classifi-cat-or

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifi-cat-or
  namespace: dhge
spec:
  selector:
    matchLabels:
      app: classifi-cat-or
  template:
    metadata:
      labels:
        app: classifi-cat-or
    spec:
      containers:
      - image: gewuerznud3l/classifi-cat-or:latest
        name: classifi-cat-or
        imagePullPolicy: Always
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node.kubernetes.io/instance-type # all nodes should have 'k3s'
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchExpressions:
          - key: app
            operator: Exists